function y = preprocess(x)
%  预处理输入 x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 12-Mar-2024 01:35:20

y = smoothdata(x,'movmedian');
